config/routes.rb
Rails.application.routes.draw do
  resources :restaurantes
  get 'pages/about'

  get 'pages/contact'

  root 'restaurantes#index'

end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  before_action :set_restaurante, only: [:show, :edit, :update, :destroy]

  # GET /restaurantes
  # GET /restaurantes.json
  def index
    @restaurantes = Restaurante.all
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.json
  def show
  end

  # GET /restaurantes/new
  def new
    @restaurante = Restaurante.new
  end

  # GET /restaurantes/1/edit
  def edit
  end

  # POST /restaurantes
  # POST /restaurantes.json
  def create
    @restaurante = Restaurante.new(restaurante_params)

    respond_to do |format|
      if @restaurante.save
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully created.' }
        format.json { render :show, status: :created, location: @restaurante }
      else
        format.html { render :new }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurantes/1
  # PATCH/PUT /restaurantes/1.json
  def update
    respond_to do |format|
      if @restaurante.update(restaurante_params)
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurante }
      else
        format.html { render :edit }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1
  # DELETE /restaurantes/1.json
  def destroy
    @restaurante.destroy
    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: 'Restaurante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurante
      @restaurante = Restaurante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurante_params
      params.require(:restaurante).permit(:name, :address, :phone, :website)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/layouts/_bootstrap.html.erb
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<p>Derechos Reservados SEAL2016</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">YelpDemo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About</a></li>
        <li><a href="/pages/contact">Contact</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Busqueda">
        </div>
        <button type="submit" class="btn btn-default">Buscar</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelpdemo</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%=render 'layouts/bootstrap' %>

</head>


<body>

<%=render 'layouts/navbar' %>
<div class="container-fluid">
  <%= yield %>

  <%=render 'layouts/footer' %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Bienvenido a la pagina inicial demo</h1>
<p>Esta página fué desarrollada para seguir un <a href="http://www.baserails.com">curso</a> para aprender a programar en ruby on rails. Inscríbase y comience a aprender hoy mismo.</p>

app/views/pages/contact.html.erb
<h1>Queremos escuchar de ustedes</h1>
<p>Contactenos en gilbertoc@seal.mx</p>

app/views/restaurantes/_form.html.erb
<%= form_for(@restaurante) do |f| %>
  <% if @restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
      <% @restaurante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurantes/edit.html.erb
<h1>Editing Restaurante</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurante, class: "btn btn-link" %> |
<%= link_to 'Back', restaurantes_path, class: "btn btn-link" %>

app/views/restaurantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurantes</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurantes.each do |restaurante| %>
      <tr>
        <td><%= restaurante.name %></td>
        <td><%= restaurante.address %></td>
        <td><%= restaurante.phone %></td>
        <td><%= restaurante.website %></td>
        <td><%= link_to 'Show', restaurante, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_restaurante_path(restaurante), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', restaurante, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurante', new_restaurante_path %>

app/views/restaurantes/new.html.erb
<h1>New Restaurante</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurantes_path, class: "btn btn-link" %>

app/views/restaurantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurante.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurante.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @restaurante.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @restaurante.website %>
</p>

<%= link_to 'Edit', edit_restaurante_path(@restaurante), class: "btn btn-link" %> |
<%= link_to 'Back', restaurantes_path, class: "btn btn-link" %>